### ISSUE TITLE
Aplicación crashea si hay producto sin imagen

### ISSUE THREAD

**Issue by pitazzo** [unizar-30226-2019-08/FrontendMobile#34]
**Descripción del bug**
La app crashea si hay algún producto sin imagen

**Reproducción del error**
Pasos para reproducir el error
1. Cargar producto sin imagen en el servidor
2. Acceder a la pantalla principal

**Comportamiento esperado**
Comportamiento robusto, mostrar _placeholder_ o similar.

**Capturas de pantalla**

**Dispositovo (please complete the following information):**
 - Modelo: [p.e. OnePlus 5/simulador...]
 - SO: [p.e. Android 8.1]
 - Versión [p.e. 22]

**Comment by rankern** [comment]
Se ha añadido una imagen a "/assets/image/" para mostrar cuando no existan imagenes. Faltaría realizar la imagen personal de Bookalo.

En la vista de un único producto, se ve dicha imagen aunque en la ventana principal se ve completamente en blanco al no encontrar NetworkImage la url de 'assets', dado que no es una URL.

**Comment by rankern** [comment]
debería estar solucionado
